(rule
 (targets g.ml)
 (deps ../stubgen/ffi_ml_oski_types_stubgen.exe)
 (action
  (with-stdout-to
   %{targets}
   (run %{deps}))))

(library
 (name oski_types)
 (public_name oski.types)
 (synopsis "Ctypes bindings that describe the SKIA FFI")
 (libraries oski.bindings.types oski.bindings.c ctypes.stubs ctypes))
