(rule
 (targets g.ml)
 (deps ../stubgen/ffi_stubgen.exe)
 (action
  (with-stdout-to
   %{targets}
   (run %{deps} -ml))))

(rule
 (targets oski_stubs.c)
 (deps
  (:stubgen ../stubgen/ffi_stubgen.exe)
  ../../vendor/prefix/skia/include/c/sk_types.h)
 (action
  (with-stdout-to
   %{targets}
   (run %{stubgen} -c))))

(library
 (name oski_ffi)
 (public_name oski.ffi)
 (modules g m)
 (flags
  (:standard -w -9-27-32-34))
 (libraries oski.bindings oski.types oski.bindings.c ctypes.stubs)
 (foreign_stubs
  (language c)
  (names oski_stubs)
  (flags
   (:include ../../config/c_flags.sexp)))
 (library_flags
  (:include ../../config/flags.sexp))
 (c_library_flags
  (:include ../../config/c_library_flags.sexp)))
