(library
 (name oski_bindings_c)
 (public_name oski.bindings.c)
 (preprocess no_preprocessing)
 (foreign_archives oskic))

(rule
 (targets liboskic%{ext_lib} dlloskic%{ext_dll})
 (deps bindings%{ext_obj} svgdom%{ext_obj} c_stubs%{ext_obj})
 (action
  (run
   ocamlmklib
   -o
   oskic
   %{read-lines:../../config/cxx_library_flags.txt}
   %{deps})))

(rule
 (targets bindings%{ext_obj})
 (deps
  oski_types.h
  (:cpp bindings.h bindings.cpp)
  ../../vendor/prefix/skia/lib
  ../../config/cxx_flags.sexp)
 (action
  (run %{cxx} %{read-lines:../../config/cxx_flags.txt} -c %{cpp})))

(rule
 (targets svgdom%{ext_obj})
 (deps
  oski_types.h
  (:cpp svgdom.h svgdom.cpp)
  ../../vendor/prefix/skia/lib
  ../../config/cxx_flags.sexp)
 (action
  (run %{cxx} %{read-lines:../../config/cxx_flags.txt} -c %{cpp})))

(rule
 (targets c_stubs%{ext_obj})
 (deps
  oski_types.h
  (:c c_stubs.h c_stubs.c)
  ../../vendor/prefix/skia/lib
  ../../config/cxx_flags.sexp)
 (action
  (run %{cc} %{read-lines:../../config/c_flags.txt} -c %{c})))
